<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('trs_producers', function (Blueprint $table) {
            $table->id();
            $table->string('prov')->nullable();
            $table->string('company')->nullable();
            $table->string('tsr_product')->nullable();
            $table->string('product_code')->nullable();
            $table->string('email')->nullable();
            $table->timestamps();
        });

        DB::table('trs_producers')->insert([
            [
                'prov' => 'North Sumatra',
                'company' => 'ANUGRAH SIBOLGA LESTARI, PT',
                'tsr_product' => 'SIR (10, 20, 10 VK60, 20 VK60)',
                'product_code' => 'SFU',
                'email' => 'asl@anugrah-group.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'BRIDGESTONE SUMATRA RUBBER ESTATE, PT',
                'tsr_product' => 'SIR (3WF, SIR LoV, 10, 20)',
                'product_code' => 'SAU',
                'email' => 'shuhei-yamagata@bridgestone@com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'DARMASINDO INTI KARET, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBX',
                'email' => 'sbx@darmasindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KAPUAS BESAR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEY',
                'email' => 'kb.pontianak@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KIRANA SAPTA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFF',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Sungai Rumbiya',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'SBT',
                'email' => 'http://www.londonsumatra.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Palangisang',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'CAA',
                'email' => 'http://www.londonsumatra.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'MADJIN CRUMB RUBBER FACTORY, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCR',
                'email' => 'madjincr@nusa.net.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'NUSIRA, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAD',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PANTJA SURYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SBV',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Gunung Para',
                'tsr_product' => 'SIR (10, 20), RSS',
                'product_code' => 'SCS',
                'email' => 'pengolahan@ptpn3.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLYKENCANA RAYA, PT',
                'tsr_product' => 'SIR (10, 10CV, 20, 20CV)',
                'product_code' => 'SGY',
                'email' => 'eksport@polykencanaraya.com, general@polykencanaraya.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POTENSI BUMI SAKTI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => null,
                'email' => 'rudi@potensibumisakti.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-RANTAU PRAPAT, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCM',
                'email' => 'hocklie.expordepmt@gmail.com, hockliemdn@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-SUNGGAL, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDH',
                'email' => 'hocklie.expordepmt@gmail.com, hockliemdn@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Tanah Bersih',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SBU',
                'email' => 'head_office@socfindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Aek Pemienke',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SDM',
                'email' => 'head_office@socfindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'VIRGINIA INDONESIA RUBBER COMPANY, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAH',
                'email' => 'virco@live.com, vircomedan1@outlook.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'WIPOLIMEX RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBI',
                'email' => 'wipolimexraya@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PERKEBUNAN NUSANTARA IV REGIONAL 3, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SES',
                'email' => 'pemasaran.ptpn5@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLY BANGKINANG RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGF',
                'email' => 'polybangkinangraya@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PULAU BINTAN DJAYA, PT',
                'tsr_product' => 'SIR (5, 10, 10VK, 20, 20VK)',
                'product_code' => 'SAR',
                'email' => 'office@pulaubintandyaja.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TIRTA SARI SURYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCE',
                'email' => 'tirtasarisurya@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'ABAISIAT RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFB',
                'email' => 'admin@abaisiatraya.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'FAMILI RAYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SAZ',
                'email' => 'pt_familirayacrf@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KILANG LIMA GUNUNG, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCA',
                'email' => 'ptkilanglimagunung@yahoo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TELUK LUAS, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCB',
                'email' => 'telukluas@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFY',
                'email' => 'abp.ga@ptabp.co.id ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANUGRAH BUNGO LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGJ',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAK',
                'email' => 'info@kiranamegatara.com ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS JUJUHAN, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SEU',
                'email' => 'info@kiranamegatara.com ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HEVEA GE, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGB',
                'email' => '(62-21) 6907249',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCL',
                'email' => '(62-741) 34090 ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'KARET BATIN DELAPAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHB',
                'email' => 'SHB@karetbatin8.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBG',
                'email' => '(62-741) 581980, 581981',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'STAR RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGW',
                'email' => 'www.sritranggroup.com ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'BUKIT ANGKASA MAKMUR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEK',
                'email' => 'fenny_bam@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'PAMOR GANDA, PT',
                'tsr_product' => 'SIR (3CV, 10, 20)',
                'product_code' => 'SFL',
                'email' => 'pamorganda_bengkulu@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SED',
                'email' => 'abp.ga@ptabp.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'ASA RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => null,
                'email' => 'asarubber@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG AGUNG PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGX',
                'email' => 'enquiry@bintanggasing.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG GASING PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFX',
                'email' => 'enquiry@bintanggasing.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BUMI BELITI ABADI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGG',
                'email' => 'factory@bumibelitiabadi.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'FAJAR BERSERI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGK',
                'email' => 'pt.fajarberseri@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'GADJAH RUKU, PT',
                'tsr_product' => 'SIR (5, 10, 20)',
                'product_code' => 'SBF',
                'email' => 'irwan.mualim@gadjahruku.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK I, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SDR',
                'email' => '(62-711) 712680; 712681 ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK II, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SEA',
                'email' => '(62-711) 7440705; 7440018, ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCX',
                'email' => '(62-711) 540931; 541343; 542182 ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOKTONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGO',
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA MUSI PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFN',
                'email' => '(62-714) 322690',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA PERMATA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGP',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA WINDU, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFW',
                'email' => '(62-733) 4100202',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KARINI UTAMA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SFA',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LINGGA DJAJA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEE',
                'email' => 'lingga.see@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LONDON SUMATRA INDONESIA Tbk, PT',
                'tsr_product' => 'SIR (3CV, 3L, 10, 20)',
                'product_code' => 'SGD',
                'email' => '(62-711) 351035',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'MARDEC MUSI LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFQ',
                'email' => '(62-711) 356060',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PANCASAMUDERA SIMPATI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SDO',
                'email' => 'panca_s@sdo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PINAGO UTAMA Tbk, PT',
                'tsr_product' => 'SIR (5, 10, 20), RSS1',
                'product_code' => 'SFK',
                'email' => 'hasan.tantri@gmail.com, ratna.sari@pinagoutama.com,helen.riana@pinagoutama.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT I, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAQ',
                'email' => 'trading@prasidha.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT II, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEQ',
                'email' => 'trading@prasidha.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDQ',
                'email' => '(62-711) 510044; 513915; 512951',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'SUNAN RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCY',
                'email' => '(62-711) 511809',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'WARNA AGUNG SELATAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHA',
                'email' => 'warnaagungselatansha@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'ANUGRAH SIBOLGA LESTARI, PT',
                'tsr_product' => 'SIR (10, 20, 10 VK60, 20 VK60)',
                'product_code' => 'SFU',
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'BRIDGESTONE SUMATRA RUBBER ESTATE, PT',
                'tsr_product' => 'SIR (3WF, SIR LoV, 10, 20)',
                'product_code' => 'SAU',
                'email' => 'shuhei-yamagata@bridgestone@com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'DARMASINDO INTI KARET, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBX',
                'email' => 'sbx@darmasindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KAPUAS BESAR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEY',
                'email' => 'kb.pontianak@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KIRANA SAPTA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFF',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'LONDON SUMATRA INDONESIA Tbk, PP PT',
                'tsr_product' => null,
                'product_code' => null,
                'email' => 'http://www.londonsumatra.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Sungai Rumbiya',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'SBT',
                'email' => 'http://www.londonsumatra.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Palangisang',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'CAA',
                'email' => 'http://www.londonsumatra.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'MADJIN CRUMB RUBBER FACTORY, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCR',
                'email' => 'madjincr@nusa.net.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'NUSIRA, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAD',
                'email' => '(62-61) 7867773',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PANTJA SURYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SBV',
                'email' => '(62-61) 7867773',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PERKEBUNAN NUSANTARA IV REGIONAL 1, PT',
                'tsr_product' => null,
                'product_code' => null,
                'email' => 'pengolahan@ptpn3.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Gunung Para',
                'tsr_product' => 'SIR (10, 20), RSS',
                'product_code' => 'SCS',
                'email' => 'pengolahan@ptpn3.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLYKENCANA RAYA, PT',
                'tsr_product' => 'SIR (10, 10CV, 20, 20CV)',
                'product_code' => 'SGY',
                'email' => 'eksport@polykencanaraya.com, general@polykencanaraya.com ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POTENSI BUMI SAKTI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => null,
                'email' => 'rudi@potensibumisakti.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-RANTAU PRAPAT, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCM',
                'email' => 'hocklie.expordepmt@gmail.com; hockliemdn@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-SUNGGAL, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDH',
                'email' => 'hocklie.expordepmt@gmail.com; hockliemdn@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'SOCFIN INDONESIA (SOCFINDO), PT',
                'tsr_product' => null,
                'product_code' => null,
                'email' => 'head_office@socfindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Tanah Bersih',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SBU',
                'email' => 'head_office@socfindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Aek Pemienke',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SDM',
                'email' => 'head_office@socfindo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'VIRGINIA INDONESIA RUBBER COMPANY, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAH',
                'email' => 'virco@live.com, vircomedan1@outlook.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'WIPOLIMEX RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBI',
                'email' => 'wipolimexraya@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PERKEBUNAN NUSANTARA IV REGIONAL 3, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SES',
                'email' => 'pemasaran.ptpn5@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLY BANGKINANG RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGF',
                'email' => 'polybangkinangraya@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PULAU BINTAN DJAYA, PT',
                'tsr_product' => 'SIR (5, 10, 10VK, 20, 20VK)',
                'product_code' => 'SAR',
                'email' => 'office@pulaubintandyaja.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TIRTA SARI SURYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCE',
                'email' => 'tirtasarisurya@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'ABAISIAT RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFB',
                'email' => 'admin@abaisiatraya.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'FAMILI RAYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SAZ',
                'email' => 'pt_familirayacrf@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KILANG LIMA GUNUNG, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCA',
                'email' => 'ptkilanglimagunung@yahoo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TELUK LUAS, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCB',
                'email' => 'telukluas@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFY',
                'email' => 'abp.ga@ptabp.co.id ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANUGRAH BUNGO LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGJ',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAK',
                'email' => '082882024114, 082882022224  ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS JUJUHAN, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SEU',
                'email' => '(62-754) 583020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HEVEA GE, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGB',
                'email' => '(62-21) 6907249',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCL',
                'email' => '(62-741) 34090',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'KARET BATIN DELAPAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHB',
                'email' => 'SHB@karetbatin8.com, ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBG',
                'email' => 'admin@karetbatin8.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'STAR RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGW',
                'email' => 'www.sritranggroup.com ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'BUKIT ANGKASA MAKMUR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEK',
                'email' => 'fenny_bam@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'PAMOR GANDA, PT',
                'tsr_product' => 'SIR (3CV, 10, 20)',
                'product_code' => 'SFL',
                'email' => 'pamorganda_bengkulu@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bengkulu
            [
                'prov' => 'Bengkulu',
                'company' => 'BUKIT ANGKASA MAKMUR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEK',
                'email' => 'fenny_bam@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'PAMOR GANDA, PT',
                'tsr_product' => 'SIR (3CV, 10, 20)',
                'product_code' => 'SFL',
                'email' => 'pamorganda_bengkulu@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // South Sumatra
            [
                'prov' => 'South Sumatra',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SED',
                'email' => 'abp.ga@ptabp.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'ASA RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => null,
                'email' => 'asarubber@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG AGUNG PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGX',
                'email' => '(62-711) 317388',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG GASING PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFX',
                'email' => 'enquiry@bintanggasing.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BUMI BELITI ABADI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGG',
                'email' => 'factory@bumibelitiabadi.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'FAJAR BERSERI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGK',
                'email' => 'pt.fajarberseri@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'GADJAH RUKU, PT',
                'tsr_product' => 'SIR (5, 10, 20)',
                'product_code' => 'SBF',
                'email' => 'irwan.mualim@gadjahruku.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK I, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SDR',
                'email' => '(62-711) 712680; 712681 ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK II, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SEA',
                'email' => '(62-711) 7440705; 7440018',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCX',
                'email' => '(62-711) 540931; 541343; 542182',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA MUSI PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFN',
                'email' => '(62-714) 322690',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA PERMATA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGP',
                'email' => 'info@kiranamegatara.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA WINDU, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFW',
                'email' => '(62-733) 4100202',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KARINI UTAMA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SFA',
                'email' => '0717-9142004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LINGGA DJAJA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEE',
                'email' => 'lingga.see@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LONDON SUMATRA INDONESIA Tbk, PT',
                'tsr_product' => 'SIR (3CV, 3L, 10, 20)',
                'product_code' => 'SGD',
                'email' => '(62-711) 351035',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'MARDEC MUSI LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFQ',
                'email' => '(62-711) 356060',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PANCASAMUDERA SIMPATI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SDO',
                'email' => 'panca_s@sdo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PINAGO UTAMA Tbk, PT',
                'tsr_product' => 'SIR (5, 10, 20), RSS1',
                'product_code' => 'SFK',
                'email' => 'hasan.tantri@gmail.com, ratna.sari@pinagoutama.com, helen.riana@pinagoutama.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT I, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAQ',
                'email' => 'trading@prasidha.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT II, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEQ',
                'email' => 'trading@prasidha.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDQ',
                'email' => '(62-711) 510044; 513915; 512951',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'SUNAN RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCY',
                'email' => '(62-711) 511809',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'WARNA AGUNG SELATAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHA',
                'email' => 'warnaagungselatansha@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'INDOLATEX JAYA ABADI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SGM',
                'email' => 'ptindolatex1@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'KOMERING JAYA PERDANA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGH',
                'email' => 'ptindolatex1@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'MARDEC SIGER WAY KANAN, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SGI',
                'email' => 'lokmanulhakim.jamian@mardec.com.my',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'MENGGALA BERSERI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SGV',
                'email' => 'menggala@berseriindonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'PERKEBUNAN NUSANTARA I REGIONAL 7, PT',
                'tsr_product' => null,
                'product_code' => null,
                'email' => 'sekretariat@ptpn7.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Pematang Kiwah-Lampung',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SBQ',
                'email' => 'sekretariat@ptpn7.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Tulung Buyut-Lampung',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SEL',
                'email' => 'sekretariat@ptpn7.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Tabenan-Palembang',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SDZ',
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Baturaja-Palembang',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEG',
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Padang Pelawi-Palembang',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEP',
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Way Berulu',
                'tsr_product' => 'SIR (3L, 3WF)',
                'product_code' => null,
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'RUBBER JAYA LAMPUNG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGN',
                'email' => 'rubberjaya@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'WAYKANDIS, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SAW',
                'email' => 'waykandis.saw@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'BINTANG BORNEO PERSADA, PT',
                'tsr_product' => 'SIR (10, 20, 10CV, 20CV)',
                'product_code' => 'KCA',
                'email' => ': trading-i@southlandglobal.com, merly@bintangborneo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'GMG SENTOSA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBM',
                'email' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAZ',
                'email' => '(62-561) 883015',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'KOTA NIAGA RAYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'KBO',
                'email' => 'trading-i@southlandglobal.com,general@kotaniagaraya.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'NEW KALBAR PROCESSORS, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'KBC',
                'email' => '(62-561) 736643; 749326 ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'STAR RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBT',
                'email' => 'www.sritranggroup.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER ALAM, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBD',
                'email' => 'djantin.sa@yahoo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER DJANTIN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAB',
                'email' => 'djantin.sa@yahoo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER DJANTIN UNIT SAMBAS, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBE',
                'email' => 'djantin.sa@yahoo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER DJANTIN UNIT SANGGAU, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBP',
                'email' => 'djantin.sa@yahoo.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BORNEO MAKMUR LESTARI, PT',
                'tsr_product' => 'SIR (10, 20, 20 Mixture)',
                'product_code' => 'KBS',
                'email' => 'jerryindra_bml@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BUMI ASRI PASAMAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBK',
                'email' => 'bap_jkt@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BUMI BORNEO ABADI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => '--',
                'email' => 'bap_jkt@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BUMI JAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBQ',
                'email' => 'bumijayakbq@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'DARMA KALIMANTAN JAYA, PT',
                'tsr_product' => 'SIR (10, 20), Compound',
                'product_code' => 'KBG',
                'email' => 'darma.kalimantan.jaya.kbg@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'INSAN BONAFIDE, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAV',
                'email' => 'insankav@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'JHONLIN AGRO MANDIRI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KCB',
                'email' => 'khairnas0399@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KAHAYAN BERSERI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KCC',
                'email' => 'kcc@kahayanberseri.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KARIAS TABING KENCANA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAY',
                'email' => 'ktk_amt@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KARYA SEJATI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBB',
                'email' => 'pt.karyasejati@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KINTAP JAYA WATTINDO, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBX',
                'email' => 'pkr_kjw@yahoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'MULTI KUSUMA CEMERLANG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KCD',
                'email' => '(62-21) 29353610',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'NUSANTARA BATULICIN, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'KBY',
                'email' => 'nusantara.balin@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'SAMPIT INTERNATIONAL, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBF',
                'email' => 'info@sampit-international.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'WILSON LAUTAN KARET, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAU',
                'email' => 'wilsonlautankaret@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Java group
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BITUNG GUNASEJAHTERA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAN',
                'email' => 'bitung@cbn.net.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'INDO JAVA RUBBER PLANTING Co, PT',
                'tsr_product' => 'SIR (3L, 5, 10, 20)',
                'product_code' => 'DAO',
                'email' => 'marketing@jawattie.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'JADI JAYA MAKMUR, CV',
                'tsr_product' => 'SIR 20',
                'product_code' => 'DAU',
                'email' => 'jamaksmg@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KALIDUREN ESTATES, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAR',
                'email' => 'marketing@jawattie.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'NUSA ALAM RUBBER, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'DAY',
                'email' => 'pt.nusaalamrubber@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sub-unit of PTPN
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => '§ Cikumpay',
                'tsr_product' => 'SIR 10, RSS',
                'product_code' => 'DAJ',
                'email' => 'pemasarannt8@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'RABERINDO PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAQ',
                'email' => 'raberindo.p2@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'SEMESTA JAYA LESTARIE, CV',
                'tsr_product' => 'SIR 20',
                'product_code' => 'DAW',
                'email' => 'putera_semesta@hotmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'SINAR JAYA, CV',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAX',
                'email' => 'rubbersj@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('rss_producers');
    }
};
