<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('trs_producers', function (Blueprint $table) {
            $table->id();
            $table->string('prov')->nullable();
            $table->string('company')->nullable();
            $table->string('tsr_product')->nullable();
            $table->string('product_code')->nullable();
            $table->string('page')->nullable();
            $table->timestamps();
        });

        DB::table('trs_producers')->insert([
            [
                'prov' => 'North Sumatra',
                'company' => 'ANUGRAH SIBOLGA LESTARI, PT',
                'tsr_product' => 'SIR (10, 20, 10 VK60, 20 VK60)',
                'product_code' => 'SFU',
                'page' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'BAKRIE SUMATERA PLANTATIONS Tbk, PT',
                'tsr_product' => 'SIR (3L, 3CV, 10, 10VK, 20, 20VK) Latex Centrifuged',
                'product_code' => 'SBZ',
                'page' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'BRIDGESTONE SUMATRA RUBBER ESTATE, PT',
                'tsr_product' => 'SIR (3WF, SIR LoV, 10, 20)',
                'product_code' => 'SAU',
                'page' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'DARMASINDO INTI KARET, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBX',
                'page' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KAPUAS BESAR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEY',
                'page' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KIRANA SAPTA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFF',
                'page' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Sungai Rumbiya',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'SBT',
                'page' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Palangisang',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'CAA',
                'page' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'MADJIN CRUMB RUBBER FACTORY, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCR',
                'page' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'NUSIRA, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAD',
                'page' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PANTJA SURYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SBV',
                'page' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Membang Muda',
                'tsr_product' => 'SIR (10, 20), Latex Centrifuged',
                'product_code' => 'SBM',
                'page' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Gunung Para',
                'tsr_product' => 'SIR (10, 20), RSS',
                'product_code' => 'SCS',
                'page' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLYKENCANA RAYA, PT',
                'tsr_product' => 'SIR (10, 10CV, 20, 20CV)',
                'product_code' => 'SGY',
                'page' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POTENSI BUMI SAKTI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => null,
                'page' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PRIMA INDO RUBBER, PT',
                'tsr_product' => 'SIR 20, RSS, Lateks Pekat',
                'product_code' => 'SHX',
                'page' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-RANTAU PRAPAT, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCM',
                'page' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-SUNGGAL, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDH',
                'page' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Tanah Bersih',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SBU',
                'page' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'Aek Pemienke',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SDM',
                'page' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'VIRGINIA INDONESIA RUBBER COMPANY, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAH',
                'page' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'WIPOLIMEX RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBI',
                'page' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PERKEBUNAN NUSANTARA IV REGIONAL 3, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SES',
                'page' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLY BANGKINANG RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGF',
                'page' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PULAU BINTAN DJAYA, PT',
                'tsr_product' => 'SIR (5, 10, 10VK, 20, 20VK)',
                'product_code' => 'SAR',
                'page' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TIRTA SARI SURYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCE',
                'page' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'ABAISIAT RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFB',
                'page' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'FAMILI RAYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SAZ',
                'page' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KILANG LIMA GUNUNG, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCA',
                'page' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TELUK LUAS, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCB',
                'page' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFY',
                'page' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANUGRAH BUNGO LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGJ',
                'page' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAK',
                'page' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS JUJUHAN, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SEU',
                'page' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HEVEA GE, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGB',
                'page' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCL',
                'page' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'KARET BATIN DELAPAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHB',
                'page' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBG',
                'page' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'STAR RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGW',
                'page' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'BUKIT ANGKASA MAKMUR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEK',
                'page' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'PAMOR GANDA, PT',
                'tsr_product' => 'SIR (3CV, 10, 20)',
                'product_code' => 'SFL',
                'page' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SED',
                'page' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'ASA RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => null,
                'page' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG AGUNG PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGX',
                'page' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG GASING PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFX',
                'page' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BUMI BELITI ABADI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGG',
                'page' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'FAJAR BERSERI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGK',
                'page' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'GADJAH RUKU, PT',
                'tsr_product' => 'SIR (5, 10, 20)',
                'product_code' => 'SBF',
                'page' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK I, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SDR',
                'page' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK II, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SEA',
                'page' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCX',
                'page' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOKTONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGO',
                'page' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA MUSI PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFN',
                'page' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA PERMATA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGP',
                'page' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA WINDU, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFW',
                'page' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KARINI UTAMA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SFA',
                'page' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LINGGA DJAJA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEE',
                'page' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LONDON SUMATRA INDONESIA Tbk, PT',
                'tsr_product' => 'SIR (3CV, 3L, 10, 20)',
                'product_code' => 'SGD',
                'page' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'MARDEC MUSI LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFQ',
                'page' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PANCASAMUDERA SIMPATI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SDO',
                'page' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PINAGO UTAMA Tbk, PT',
                'tsr_product' => 'SIR (5, 10, 20), RSS1',
                'product_code' => 'SFK',
                'page' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT I, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAQ',
                'page' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT II, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEQ',
                'page' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDQ',
                'page' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'SRITRANG LINGGA INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20, Compound, C Latex)',
                'product_code' => 'SFZ',
                'page' => 51,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'SUNAN RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCY',
                'page' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'WARNA AGUNG SELATAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHA',
                'page' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'ANUGRAH SIBOLGA LESTARI, PT',
                'tsr_product' => 'SIR (10, 20, 10 VK60, 20 VK60)',
                'product_code' => 'SFU',
                'page' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'BAKRIE SUMATERA PLANTATIONS Tbk, PT',
                'tsr_product' => 'SIR (3L, 3CV, 10, 10VK, 20, 20VK), Latex Centrifuged',
                'product_code' => 'SBZ',
                'page' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'BRIDGESTONE SUMATRA RUBBER ESTATE, PT',
                'tsr_product' => 'SIR (3WF, SIR LoV, 10, 20)',
                'product_code' => 'SAU',
                'page' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'DARMASINDO INTI KARET, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBX',
                'page' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KAPUAS BESAR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEY',
                'page' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KIRANA SAPTA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFF',
                'page' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'LONDON SUMATRA INDONESIA Tbk, PP PT',
                'tsr_product' => null,
                'product_code' => null,
                'page' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Sungai Rumbiya',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'SBT',
                'page' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Palangisang',
                'tsr_product' => 'SIR (3CV60, 3L, 10, 20)',
                'product_code' => 'CAA',
                'page' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'MADJIN CRUMB RUBBER FACTORY, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCR',
                'page' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'NUSIRA, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAD',
                'page' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PANTJA SURYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SBV',
                'page' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PERKEBUNAN NUSANTARA IV REGIONAL 1, PT',
                'tsr_product' => null,
                'product_code' => null,
                'page' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Membang Muda',
                'tsr_product' => 'SIR (10, 20), Latex Centrifuged',
                'product_code' => 'SBM',
                'page' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Gunung Para',
                'tsr_product' => 'SIR (10, 20), RSS',
                'product_code' => 'SCS',
                'page' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLYKENCANA RAYA, PT',
                'tsr_product' => 'SIR (10, 10CV, 20, 20CV)',
                'product_code' => 'SGY',
                'page' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POTENSI BUMI SAKTI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => null,
                'page' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PRIMA INDO RUBBER, PT',
                'tsr_product' => 'SIR 20, RSS, Lateks Pekat',
                'product_code' => 'SHX',
                'page' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-RANTAU PRAPAT, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCM',
                'page' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'RUBBER HOCK LIE-SUNGGAL, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDH',
                'page' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'SOCFIN INDONESIA (SOCFINDO), PT',
                'tsr_product' => null,
                'product_code' => null,
                'page' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Tanah Bersih',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SBU',
                'page' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => '§ Aek Pemienke',
                'tsr_product' => 'SIR (3CV, 10)',
                'product_code' => 'SDM',
                'page' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'VIRGINIA INDONESIA RUBBER COMPANY, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAH',
                'page' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'WIPOLIMEX RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBI',
                'page' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PERKEBUNAN NUSANTARA IV REGIONAL 3, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SES',
                'page' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'POLY BANGKINANG RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGF',
                'page' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'PULAU BINTAN DJAYA, PT',
                'tsr_product' => 'SIR (5, 10, 10VK, 20, 20VK)',
                'product_code' => 'SAR',
                'page' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TIRTA SARI SURYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCE',
                'page' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'ABAISIAT RAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFB',
                'page' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'FAMILI RAYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SAZ',
                'page' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'KILANG LIMA GUNUNG, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SCA',
                'page' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'North Sumatra',
                'company' => 'TELUK LUAS, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCB',
                'page' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFY',
                'page' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'ANUGRAH BUNGO LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGJ',
                'page' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SAK',
                'page' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'DJAMBI WARAS JUJUHAN, PT',
                'tsr_product' => 'SIR (10, 20, 20VK)',
                'product_code' => 'SEU',
                'page' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HEVEA GE, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGB',
                'page' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCL',
                'page' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'KARET BATIN DELAPAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHB',
                'page' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SBG',
                'page' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Jambi',
                'company' => 'STAR RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGW',
                'page' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'BUKIT ANGKASA MAKMUR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEK',
                'page' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'PAMOR GANDA, PT',
                'tsr_product' => 'SIR (3CV, 10, 20)',
                'product_code' => 'SFL',
                'page' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bengkulu
            [
                'prov' => 'Bengkulu',
                'company' => 'BUKIT ANGKASA MAKMUR, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEK',
                'page' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Bengkulu',
                'company' => 'PAMOR GANDA, PT',
                'tsr_product' => 'SIR (3CV, 10, 20)',
                'product_code' => 'SFL',
                'page' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // South Sumatra
            [
                'prov' => 'South Sumatra',
                'company' => 'ANEKA BUMI PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SED',
                'page' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'ASA RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => null,
                'page' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG AGUNG PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGX',
                'page' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BINTANG GASING PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFX',
                'page' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'BUMI BELITI ABADI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGG',
                'page' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'FAJAR BERSERI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGK',
                'page' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'GADJAH RUKU, PT',
                'tsr_product' => 'SIR (5, 10, 20)',
                'product_code' => 'SBF',
                'page' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK I, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SDR',
                'page' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HEVEA MK II, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'SEA',
                'page' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCX',
                'page' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'HOKTONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGO',
                'page' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA MUSI PERSADA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFN',
                'page' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA PERMATA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGP',
                'page' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KIRANA WINDU, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFW',
                'page' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'KARINI UTAMA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SFA',
                'page' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LINGGA DJAJA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEE',
                'page' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'LONDON SUMATRA INDONESIA Tbk, PT',
                'tsr_product' => 'SIR (3CV, 3L, 10, 20)',
                'product_code' => 'SGD',
                'page' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'MARDEC MUSI LESTARI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SFQ',
                'page' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PANCASAMUDERA SIMPATI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SDO',
                'page' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PINAGO UTAMA Tbk, PT',
                'tsr_product' => 'SIR (5, 10, 20), RSS1',
                'product_code' => 'SFK',
                'page' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT I, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SAQ',
                'page' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'PRASIDHA ANEKA NIAGA Tbk UNIT II, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEQ',
                'page' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'REMCO RUBBER INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SDQ',
                'page' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'SRITRANG LINGGA INDONESIA, PT',
                'tsr_product' => 'SIR (10, 20), Compound, C Latex',
                'product_code' => 'SFZ',
                'page' => 51,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'SUNAN RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SCY',
                'page' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South Sumatra',
                'company' => 'WARNA AGUNG SELATAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SHA',
                'page' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'INDOLATEX JAYA ABADI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SGM',
                'page' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'KOMERING JAYA PERDANA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGH',
                'page' => 56,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'MARDEC SIGER WAY KANAN, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SGI',
                'page' => 56,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'MENGGALA BERSERI, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SGV',
                'page' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'PERKEBUNAN NUSANTARA I REGIONAL 7, PT',
                'tsr_product' => null,
                'product_code' => null,
                'page' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Pematang Kiwah-Lampung',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SBQ',
                'page' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Tulung Buyut-Lampung',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SEL',
                'page' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Tabenan-Palembang',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SDZ',
                'page' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Baturaja-Palembang',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEG',
                'page' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Padang Pelawi-Palembang',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SEP',
                'page' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => '§ Way Berulu',
                'tsr_product' => 'SIR (3L, 3WF)',
                'product_code' => null,
                'page' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'RUBBER JAYA LAMPUNG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'SGN',
                'page' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'SILVA INHUTANI LAMPUNG, PT',
                'tsr_product' => 'SIR (10, 20), C Latex 60%',
                'product_code' => 'SGS',
                'page' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'Lampung',
                'company' => 'WAYKANDIS, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'SAW',
                'page' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'BINTANG BORNEO PERSADA, PT',
                'tsr_product' => 'SIR (10, 20, 10CV, 20CV)',
                'product_code' => 'KCA',
                'page' => 62,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'GMG SENTOSA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBM',
                'page' => 63,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'HOK TONG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAZ',
                'page' => 64,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'KOTA NIAGA RAYA, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'KBO',
                'page' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'NEW KALBAR PROCESSORS, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'KBC',
                'page' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'STAR RUBBER, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBT',
                'page' => 66,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER ALAM, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBD',
                'page' => 67,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER DJANTIN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAB',
                'page' => 68,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER DJANTIN UNIT SAMBAS, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBE',
                'page' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'West Kalimantan',
                'company' => 'SUMBER DJANTIN UNIT SANGGAU, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBP',
                'page' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BORNEO MAKMUR LESTARI, PT',
                'tsr_product' => 'SIR (10, 20, 20 Mixture)',
                'product_code' => 'KBS',
                'page' => 72,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BUMI ASRI PASAMAN, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBK',
                'page' => 73,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BUMI BORNEO ABADI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => '--',
                'page' => 74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BUMI JAYA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBQ',
                'page' => 74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'DARMA KALIMANTAN JAYA, PT',
                'tsr_product' => 'SIR (10, 20), Compound',
                'product_code' => 'KBG',
                'page' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'INSAN BONAFIDE, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAV',
                'page' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'JHONLIN AGRO MANDIRI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KCB',
                'page' => 77,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KAHAYAN BERSERI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KCC',
                'page' => 77,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KARIAS TABING KENCANA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAY',
                'page' => 78,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KARYA SEJATI, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBB',
                'page' => 78,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KINTAP JAYA WATTINDO, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBX',
                'page' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'MULTI KUSUMA CEMERLANG, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KCD',
                'page' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'NUSANTARA BATULICIN, PT',
                'tsr_product' => 'SIR 20',
                'product_code' => 'KBY',
                'page' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'SAMPIT INTERNATIONAL, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KBF',
                'page' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'WILSON LAUTAN KARET, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'KAU',
                'page' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Java group
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'BITUNG GUNASEJAHTERA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAN',
                'page' => 83,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'INDO JAVA RUBBER PLANTING Co, PT',
                'tsr_product' => 'SIR (3L, 5, 10, 20)',
                'product_code' => 'DAO',
                'page' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'JADI JAYA MAKMUR, CV',
                'tsr_product' => 'SIR 20',
                'product_code' => 'DAU',
                'page' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'KALIDUREN ESTATES, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAR',
                'page' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'NUSA ALAM RUBBER, PT',
                'tsr_product' => 'SIR (10, 20, 10VK, 20VK)',
                'product_code' => 'DAY',
                'page' => 86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sub-unit of PTPN
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => '§ Cikumpay',
                'tsr_product' => 'SIR 10, RSS',
                'product_code' => 'DAJ',
                'page' => 86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'RABERINDO PRATAMA, PT',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAQ',
                'page' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'SEMESTA JAYA LESTARIE, CV',
                'tsr_product' => 'SIR 20',
                'product_code' => 'DAW',
                'page' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prov' => 'South-Central-East Kalimantan',
                'company' => 'SINAR JAYA, CV',
                'tsr_product' => 'SIR (10, 20)',
                'product_code' => 'DAX',
                'page' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('rss_producers');
    }
};
